export type StudentType = {
    id: string,
    university: string,
    walletPoint: number,
    majorId: string,
    fullName: string,
    avatarUrl: string,
    gender: string,
    birthday: string,
    userName: string,
    email: string,
    phoneNumber: string,
    emailConfirmed: boolean,
    lockoutEnd: string,
    lockoutEnabled: boolean,
    createdBy: string,
    createdOn: string,
    updatedBy: string,
    updatedOn: string
  }